name: Deploy Docs and Demo on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: yarn install

    - name: Build documentation
      run: yarn docs:prod

    - name: Build demo
      run: yarn demo:prod

    - name: Create deployment directory
      run: mkdir -p ./public

    - name: Move documentation to public/docs
      run: mv ./docs ./public/docs

    - name: Move dist-demo to public/demo
      run: mv ./dist-demo ./public/demo

    - name: Deploy to GitHub Pages
      uses: jamesives/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: public
        clean: true
        token: ${{ secrets.GITHUB_TOKEN }}
